"""Public domain contracts for dynamic schema identity, lifecycle, and field types.

This surface intentionally excludes persistence, providers, and mutable aggregate
implementations. Later schema passes will extend it with versioned definition and
application-port contracts.

@skyhook-implements REQ-003
@skyhook-implements NFR-008
@skyhook-story 4PJTJVE73D2MN7GT64T48S05HT
"""

from evidentia.modules.schemas.application.evolution import (
    InspectedSchemaPackage,
    SchemaImportPreview,
    SchemaPackageKind,
    exported_package_content,
    inspect_schema_package,
    preview_schema_import,
)
from evidentia.modules.schemas.application.interchange import (
    INTERCHANGE_FORMAT,
    INTERCHANGE_VERSION,
    SchemaInterchangeEnvelope,
    export_schema,
    export_schema_draft,
    export_schema_draft_content,
    import_schema,
    import_schema_draft_content,
)
from evidentia.modules.schemas.application.manage_schema import (
    SCHEMAS_PUBLISH,
    SCHEMAS_READ,
    SCHEMAS_WRITE,
    ManageSchemaLifecycle,
    PublishedSchemaDraft,
    SchemaArtifactCatalog,
    SchemaAuthorizationError,
    SchemaCommandContext,
    SchemaDraftContent,
)
from evidentia.modules.schemas.application.migration import (
    ProposedRevisionPlan,
    RevisionPlanKind,
    plan_reprocessing,
    plan_schema_migration,
)
from evidentia.modules.schemas.application.publish_schema import (
    ArtifactKey,
    PublicationProvenance,
    SchemaDraft,
    SchemaPublication,
    publish_schema,
)
from evidentia.modules.schemas.application.resolve_schema import resolve_schema
from evidentia.modules.schemas.domain.artifact_links import (
    ArtifactBindings,
    PublishedArtifactReference,
    SchemaArtifactKind,
)
from evidentia.modules.schemas.domain.compatibility import (
    CompatibilityLevel,
    CompatibilityReport,
    SchemaChange,
    SchemaChangeCode,
    compare_schema_versions,
)
from evidentia.modules.schemas.domain.composition import (
    CompositionConflict,
    CompositionConflictCode,
    CompositionDirective,
    CompositionResult,
    FieldAlias,
    FieldMapping,
    FieldOrigin,
    FieldReplacement,
    FieldSelector,
    ResolvedSchema,
    ResolvedSchemaIdentity,
)
from evidentia.modules.schemas.domain.definitions import (
    Cardinality,
    FieldDefinition,
    FieldType,
    ValueDefinition,
    ensure_unique_root_fields,
)
from evidentia.modules.schemas.domain.field_types import (
    ArrayType,
    ArtifactReferenceType,
    ArtifactReferenceValue,
    BooleanType,
    DateTimeType,
    DateType,
    DecimalType,
    EnumType,
    ExtensionType,
    FieldTypeKind,
    IdentifierType,
    IntegerType,
    MoneyType,
    MoneyValue,
    ObjectType,
    ReferenceType,
    ReferenceValue,
    StringType,
    TableType,
)
from evidentia.modules.schemas.domain.identity import (
    FieldKey,
    FieldPath,
    ReleaseLabel,
    SchemaId,
    SchemaModuleId,
    SchemaVersion,
)
from evidentia.modules.schemas.domain.lifecycle import (
    SchemaLifecycleState,
    allowed_schema_transitions,
    ensure_schema_transition,
)
from evidentia.modules.schemas.domain.modules import (
    PublishedSchemaModule,
    PublishedSchemaVersion,
    SchemaModuleReference,
)

__all__ = (
    "INTERCHANGE_FORMAT",
    "INTERCHANGE_VERSION",
    "SCHEMAS_PUBLISH",
    "SCHEMAS_READ",
    "SCHEMAS_WRITE",
    "ArrayType",
    "ArtifactBindings",
    "ArtifactKey",
    "ArtifactReferenceType",
    "ArtifactReferenceValue",
    "BooleanType",
    "Cardinality",
    "CompatibilityLevel",
    "CompatibilityReport",
    "CompositionConflict",
    "CompositionConflictCode",
    "CompositionDirective",
    "CompositionResult",
    "DateTimeType",
    "DateType",
    "DecimalType",
    "EnumType",
    "ExtensionType",
    "FieldAlias",
    "FieldDefinition",
    "FieldKey",
    "FieldMapping",
    "FieldOrigin",
    "FieldPath",
    "FieldReplacement",
    "FieldSelector",
    "FieldType",
    "FieldTypeKind",
    "IdentifierType",
    "InspectedSchemaPackage",
    "IntegerType",
    "ManageSchemaLifecycle",
    "MoneyType",
    "MoneyValue",
    "ObjectType",
    "ProposedRevisionPlan",
    "PublicationProvenance",
    "PublishedArtifactReference",
    "PublishedSchemaDraft",
    "PublishedSchemaModule",
    "PublishedSchemaVersion",
    "ReferenceType",
    "ReferenceValue",
    "ReleaseLabel",
    "ResolvedSchema",
    "ResolvedSchemaIdentity",
    "RevisionPlanKind",
    "SchemaArtifactCatalog",
    "SchemaArtifactKind",
    "SchemaAuthorizationError",
    "SchemaChange",
    "SchemaChangeCode",
    "SchemaCommandContext",
    "SchemaDraft",
    "SchemaDraftContent",
    "SchemaId",
    "SchemaImportPreview",
    "SchemaInterchangeEnvelope",
    "SchemaLifecycleState",
    "SchemaModuleId",
    "SchemaModuleReference",
    "SchemaPackageKind",
    "SchemaPublication",
    "SchemaVersion",
    "StringType",
    "TableType",
    "ValueDefinition",
    "allowed_schema_transitions",
    "compare_schema_versions",
    "ensure_schema_transition",
    "ensure_unique_root_fields",
    "export_schema",
    "export_schema_draft",
    "export_schema_draft_content",
    "exported_package_content",
    "import_schema",
    "import_schema_draft_content",
    "inspect_schema_package",
    "plan_reprocessing",
    "plan_schema_migration",
    "preview_schema_import",
    "publish_schema",
    "resolve_schema",
)
